galaxy_info:
  role_name: gathering
  description: Gather settings.
  author: NEC Corporation
  company: NEC Corporation
  license: Apache License 2.0
  min_ansible_version: 2.5
  platforms:
    - name: Windows
      versions:
        - 2012 R2
        - 2016
        - 2019
    - name: EL
      versions:
        - 7
  galaxy_tags: []
  categories: []

dependencies: []
